### ISSUE TITLE
API restarts unexpectedly after uncaught exception

### ISSUE THREAD

**Issue by 00ssh** [ElrondNetwork/api.elrond.com#665]
We have an API instance deployed in our K8s infrastructure, which we've built from the master branch and which currently **restarts** randomly. We couldn't relate it to any events and it has enough resources assigned. The error we get:
`UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".`
There were no issues with connection to Elasticsearch, Redis, MySQL and RabbitMQ that we encountered so far, though there are some 400s bad requests we can see in API logs.
Below is some of the configuration we use in case it helps troubleshooting (queueWorker is disabled).
```
network: 'mainnet'
metaChainShardId: 4294967295
useLegacyElastic: false
api:
  public: true
  private: true
  auth: false
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 1000
  transactionCompleted: false
  transactionCompletedMaxLookBehind: 100
  cacheWarmer: true
  fastWarm: false
  queueWorker: false
flags:
  useRequestCaching: true
  useKeepAliveAgent: true
  useTracing: false
  useRequestLogging: false
  useVmQueryTracing: false
  processNfts: true
  indexer-v3: false
```
Some other  errors we can see right before the restart (in case it helps with troubleshooting): 
```
{"context":"CachingService","level":"info","message":"Retries: 2","timestamp":"2022-06-04T09:40:01.406Z"}
{"level":"error","message":"Error running Keybase against cache invalidations","stack":["Lock"],"timestamp":"2022-06-04T09:40:01.406Z"}
{"body":{"args":[],"funcName":"getMetaData","scAddress":"erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqchllllsqqac4d"},"level":"error","message":"Request failed with status code 400","method":"POST","name":"Error","response":{"code":"bad_request","data":null,"error":"executeQuery: too many requests"},"stack":["Lock"],"status":400,"timestamp":"2022-06-04T09:40:01.406Z","url":"http://elrond-proxy-node-0:8079/vm-values/query"}
{"context":"PerformanceProfiler","level":"info","message":"Running Keybase against cache invalidations: 1404.877ms","timestamp":"2022-06-04T09:40:01.406Z"}
{"body":{"args":[],"funcName":"getMetaData","scAddress":"erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqhlllllsr6pyml"},"level":"error","message":"Request failed with status code 400","method":"POST","name":"Error","response":{"code":"bad_request","data":null,"error":"executeQuery: too many requests"},"stack":["ApiService"],"status":400,"timestamp":"2022-06-04T09:40:01.406Z","url":"http://elrond-proxy-node-0:8079/vm-values/query"}
{"level":"error","message":"Error in vm query for address 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqhlllllsr6pyml', function 'getMetaData', caller 'undefined', value 'undefined', args '[]'. Error message: undefined","stack":["VmQueryService"],"timestamp":"2022-06-04T09:40:01.406Z"}
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
Logs from 6/4/2022, 12:38:37 PM
```

Any idea what might be the issue?
